const userData = [
    {
      firstName: "Siddharth",
      fatherName: "Vikram Sharma",
      spouseName: "N/A",
      bloodGroup: "O+",
      status: "Unmarried",
      occupation: "Software Engineer",
      phoneNumber: "+91 9123456789",
      age: 27,
      img: "./imgSkeleton.png",
    },
    {
      firstName: "Meera",
      fatherName: "Ramesh Desai",
      spouseName: "Anil Desai",
      bloodGroup: "A+",
      status: "Married",
      occupation: "Teacher",
      phoneNumber: "+91 9123456790",
      age: 34,
      img: "./imgSkeleton.png",
    },
    {
      firstName: "Ravi",
      fatherName: "Mahesh Gupta",
      spouseName: "N/A",
      bloodGroup: "B+",
      status: "Unmarried",
      occupation: "Data Analyst",
      phoneNumber: "+91 9123456791",
      age: 29,
      img: "./imgSkeleton.png",
    },
    {
      firstName: "Sneha",
      fatherName: "Shankar Patil",
      spouseName: "N/A",
      bloodGroup: "AB+",
      status: "Unmarried",
      occupation: "Graphic Designer",
      phoneNumber: "+91 9123456792",
      age: 24,
      img: "./imgSkeleton.png",
    },
    {
      firstName: "Amit",
      fatherName: "Rajiv Nair",
      spouseName: "Pooja Nair",
      bloodGroup: "O-",
      status: "Married",
      occupation: "Accountant",
      phoneNumber: "+91 9123456793",
      age: 32,
      img: "./imgSkeleton.png",
    },
    {
      firstName: "Pooja",
      fatherName: "Sunil Verma",
      spouseName: "N/A",
      bloodGroup: "B-",
      status: "Unmarried",
      occupation: "Marketing Manager",
      phoneNumber: "+91 9123456794",
      age: 28,
      img: "./imgSkeleton.png",
    },
  ];
  
  export default userData;
  